# Site settings
title: Ju Stroh's blog
header-img: img/home-bg.jpg
email: juliens@microsoft.com
copyright_name: jstroheker.com
description: "My journey on DevOps / Open Source / Cloud"
baseurl: ""
url: "http://blog.jstroheker.com"
twitter_username: Ju_Stroh
github_username:  julienstroheker
email_username:  juliens@microsoft.com

google_tracking_id: UA-85543854-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
